[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.20"

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.2.0"
"@chainlink-contracts" = "1.3.0"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
